### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by brettlangdon** [justiniso/AssertionChain#1]
You are importing `__version__` from `setuptools`, so it is getting published to pypi as `0.6c12` not `0.1.0`.

Also, since I'm here, you don't need `requirements.txt` or `install_requires` in `setup.py`

**Comment by dujuku** [comment]
Resolved with: https://github.com/justiniso/AssertionChain/commit/801e578d5f11b965b44211e3aa2dd8a3b7daaf1a
